[package]
name = "gram"
version = "1.0.0"
author = "Gibby Free"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "4.0.0"
termsize = "0.1"
unicode-segmentation = "1.9.0"